#!/usr/bin/env bash
# Deploy backend + AI service to an Oracle Always Free ARM VM with free HTTPS.
#
#   sudo ./scripts/deploy-vm.sh <subdomain.duckdns.org> [GEMINI_API_KEY]
#
# Requirements already in place (done once on the VM):
#   - Ubuntu 22.04+/24.04 is used (change release label if needed)
set -euo pipefail

DUCK_HOST="${1:?usage: $0 <subdomain.duckdns.org> [GEMINI_API_KEY]}"
GEMINI_KEY="${2:-}"
export DEBIAN_FRONTEND=noninteractive

echo "==> Installing system packages"
apt-get update -y
apt-get install -y docker.io docker-compose-v2 git
systemctl enable --now docker

echo "==> Installing Caddy (free HTTPS) from official binary"
if ! command -v caddy >/dev/null 2>&1; then
    carch=$(dpkg --print-architecture)
    case "$carch" in
        arm64|amd64) ;;
        *) echo "unsupported arch: $carch"; exit 1 ;;
    esac
    CADDY_VER=2.8.4
    curl -fsSL "https://github.com/caddyserver/caddy/releases/download/v${CADDY_VER}/caddy_${CADDY_VER}_linux_${carch}.tar.gz" -o /tmp/caddy.tgz
    tar -xzf /tmp/caddy.tgz -C /usr/local/bin caddy
    chmod +x /usr/local/bin/caddy
    mkdir -p /etc/caddy /var/lib/caddy
    cat > /etc/systemd/system/caddy.service <<'UNIT'
[Unit]
Description=Caddy web server (automatic HTTPS)
After=network-online.target
Wants=network-online.target

[Service]
Type=notify
ExecStart=/usr/local/bin/caddy run --config /etc/caddy/Caddyfile
ExecReload=/usr/local/bin/caddy reload --config /etc/caddy/Caddyfile
TimeoutStopSec=5s
LimitNOFILE=1048576
LimitNPROC=512
CapabilityBoundingSet=CAP_NET_BIND_SERVICE
AmbientCapabilities=CAP_NET_BIND_SERVICE
NoNewPrivileges=true
Restart=on-failure

[Install]
WantedBy=multi-user.target
UNIT
    systemctl daemon-reload
    echo 'http://localhost/ { respond "caddy ok" }' > /etc/caddy/Caddyfile
    systemctl enable --now caddy
fi

REPO_URL="https://github.com/thachasornonlaor-netizen/storyboard-app.git"
APP_DIR=/opt/storyboard-app

if [ ! -d "$APP_DIR/.git" ]; then
    echo "==> Cloning repo"
    git clone "$REPO_URL" "$APP_DIR"
else
    echo "==> Updating repo"
    git -C "$APP_DIR" pull --ff-only
fi

echo "==> Writing .env"
if [ -n "$GEMINI_KEY" ]; then
    printf 'GEMINI_API_KEY=%s\n' "$GEMINI_KEY" > "$APP_DIR/.env"
else
    printf 'GEMINI_API_KEY=your_real_key_from_aistudio.google.com\n' > "$APP_DIR/.env"
    echo "!! No Gemini key given. After the build finishes, edit $APP_DIR/.env"
    echo "!! with your real key (aistudio.google.com/apikey) and re-run:"
    echo "!!   cd $APP_DIR && sudo docker compose -f docker-compose.onprem.yml up -d --build"
fi

echo "==> Building + starting backend stack (15-20 min on ARM, this is the long step)"
cd "$APP_DIR"
sudo docker compose -f docker-compose.onprem.yml up -d --build

echo "==> Configuring Caddy for free HTTPS: https://$DUCK_HOST"
rm -f /etc/caddy/Caddyfile
cat > /etc/caddy/Caddyfile <<EOF
# Autogenerated by scripts/deploy-vm.sh. Requires:
#   - $DUCK_HOST -> this VM's public IP in DuckDNS dashboard
#   - Oracle NSG allows TCP 80 + 443
$DUCK_HOST {
    reverse_proxy localhost:3001
}
EOF
systemctl reload caddy

echo "==> Health check (waiting for model load, up to 5 min)"
for i in $(seq 1 30); do
    sleep 10
    if curl -sf http://localhost:3001/api/health >/dev/null 2>&1; then break; fi
done
curl -s http://localhost:3001/api/health | python3 -m json.tool 2>/dev/null || true

echo
echo "All done. Public backend: http://localhost:3001"
echo "Frontend should point VITE_API_URL at: https://$DUCK_HOST"
echo "Verify HTTPS: curl -s https://$DUCK_HOST/api/health"
echo "SSL certificate auto-renews via Let's Encrypt (Caddy)."
echo "Runs forever: docker restart:unless-stopped + systemd caddy/docker."