import re

CATEGORIES = [
    "camera_angle",
    "shot_size",
    "camera_movement",
    "mood",
    "tone",
    "lighting",
]

# When a more specific option is detected, drop the generic options it covers
# (e.g. "extreme wide shot" should not also set "wide").
SUBSUMES = {
    "shot_size": {
        "extreme_close_up": {"close_up"},
        "medium_close_up": {"close_up"},
        "extreme_wide": {"wide"},
        "medium_wide": {"wide", "medium"},
        "two_shot": {"close_up"},
    },
    "camera_angle": {
        "worms_eye": {"low_angle"},
        "birds_eye": {"high_angle", "aerial"},
        "over_the_shoulder": {"shoulder_level"},
        "point_of_view": {"shoulder_level"},
    },
}

# Natural-language phrases that map onto the metadata filter values.
# Phrases are matched as substrings on lowercased text, longest phrase first
# so that e.g. "extreme close up" wins over "close up".
FILTER_SYNONYMS = {
    "camera_angle": [
        ("over the shoulder", "over_the_shoulder"),
        ("ots shot", "over_the_shoulder"),
        ("ots", "over_the_shoulder"),
        ("point of view", "point_of_view"),
        ("first person", "point_of_view"),
        ("pov", "point_of_view"),
        ("bird's eye", "birds_eye"),
        ("birds eye", "birds_eye"),
        ("birds-eye", "birds_eye"),
        ("top down", "birds_eye"),
        ("directly above", "birds_eye"),
        ("worm's eye", "worms_eye"),
        ("worms eye", "worms_eye"),
        ("worms-eye", "worms_eye"),
        ("looking straight up", "worms_eye"),
        ("dutch angle", "dutch_angle"),
        ("canted", "dutch_angle"),
        ("tilted camera", "dutch_angle"),
        ("eye level", "eye_level"),
        ("eye-level", "eye_level"),
        ("low angle", "low_angle"),
        ("low-angle", "low_angle"),
        ("looking up at", "low_angle"),
        ("from below", "low_angle"),
        ("hero shot", "low_angle"),
        ("high angle", "high_angle"),
        ("high-angle", "high_angle"),
        ("looking down at", "high_angle"),
        ("looking down on", "high_angle"),
        ("from above", "high_angle"),
        ("aerial", "aerial"),
        ("drone shot", "aerial"),
        ("drone", "aerial"),
        ("helicopter shot", "aerial"),
        ("establishing", "establishing"),
        ("shoulder level", "shoulder_level"),
        ("hip level", "hip_level"),
    ],
    "shot_size": [
        ("extreme close up", "extreme_close_up"),
        ("extreme close-up", "extreme_close_up"),
        ("extreme closeup", "extreme_close_up"),
        ("medium close up", "medium_close_up"),
        ("medium close-up", "medium_close_up"),
        ("medium closeup", "medium_close_up"),
        ("close up", "close_up"),
        ("close-up", "close_up"),
        ("closeup", "close_up"),
        ("extreme wide", "extreme_wide"),
        ("very wide", "extreme_wide"),
        ("medium wide", "medium_wide"),
        ("medium-wide", "medium_wide"),
        ("medium shot", "medium"),
        ("two shot", "two_shot"),
        ("two-shot", "two_shot"),
        ("wide shot", "wide"),
        ("wide", "wide"),
        ("insert shot", "insert"),
        ("insert", "insert"),
        ("full body", "wide"),
        ("cowboy shot", "medium_wide"),
    ],
    "camera_movement": [
        ("locked off", "static"),
        ("static shot", "static"),
        ("static", "static"),
        ("dolly in", "dolly_in"),
        ("dolly-in", "dolly_in"),
        ("dolly zoom", "vertigo"),
        ("vertigo", "vertigo"),
        ("push in", "push_in"),
        ("push-in", "push_in"),
        ("tracking shot", "tracking"),
        ("tracking", "tracking"),
        ("follow shot", "tracking"),
        ("steadycam", "steadicam"),
        ("steadicam", "steadicam"),
        ("handheld", "handheld"),
        ("hand held", "handheld"),
        ("crane shot", "crane"),
        ("crane", "crane"),
        ("slow pan", "slow_pan"),
        ("panning", "slow_pan"),
        ("pan", "slow_pan"),
        ("orbit", "orbit"),
        ("circular shot", "orbit"),
        ("zoom in", "zoom_in"),
        ("zooming in", "zoom_in"),
        ("zoom", "zoom_in"),
        ("snap zoom", "snap_zoom"),
    ],
    "mood": [
        ("suspenseful", "tense"),
        ("suspense", "tense"),
        ("tense", "tense"),
        ("anxious", "tense"),
        ("uneasy", "tense"),
        ("high stakes", "tense"),
        ("thriller", "tense"),
        ("peaceful", "peaceful"),
        ("serene", "peaceful"),
        ("tranquil", "peaceful"),
        ("calm", "peaceful"),
        ("melancholic", "melancholic"),
        ("melancholy", "melancholic"),
        ("wistful", "melancholic"),
        ("sad", "melancholic"),
        ("sorrowful", "melancholic"),
        ("joyful", "joyful"),
        ("joy", "joyful"),
        ("happy", "joyful"),
        ("cheerful", "joyful"),
        ("joyous", "joyful"),
        ("ominous", "ominous"),
        ("foreboding", "ominous"),
        ("menacing", "ominous"),
        ("threatening", "ominous"),
        ("impending doom", "ominous"),
        ("romantic", "romantic"),
        ("romance", "romantic"),
        ("loving", "romantic"),
        ("intimate", "romantic"),
        ("chaotic", "chaotic"),
        ("chaos", "chaotic"),
        ("frenetic", "chaotic"),
        ("turmoil", "chaotic"),
        ("mayhem", "chaotic"),
        ("mysterious", "mysterious"),
        ("mystery", "mysterious"),
        ("enigmatic", "mysterious"),
        ("intrigue", "mysterious"),
        ("eerie", "eerie"),
        ("creepy", "eerie"),
        ("uncanny", "eerie"),
        ("unsettling", "eerie"),
        ("spooky", "eerie"),
        ("dread", "dread"),
        ("terrifying", "dread"),
        ("horror", "dread"),
        ("fearful", "dread"),
        ("somber", "somber"),
        ("sombre", "somber"),
        ("solemn", "somber"),
        ("grave", "somber"),
        ("mournful", "somber"),
        ("electric", "electric"),
        ("electric energy", "electric"),
        ("energetic", "electric"),
        ("surreal", "surreal"),
        ("dreamlike", "surreal"),
        ("bizarre", "surreal"),
        ("claustrophobic", "claustrophobic"),
        ("claustrophobia", "claustrophobic"),
        ("trapped", "claustrophobic"),
        ("confined", "claustrophobic"),
        ("gritty", "gritty"),
        ("grimy", "gritty"),
        ("raw", "gritty"),
        ("hopeful", "hopeful"),
        ("optimistic", "hopeful"),
        ("uplifting", "hopeful"),
        ("whimsical", "whimsical"),
        ("playful", "whimsical"),
        ("fanciful", "whimsical"),
        ("quirky", "whimsical"),
    ],
    "tone": [
        ("high contrast", "high_contrast"),
        ("harsh contrast", "high_contrast"),
        ("golden hour", "golden_hour"),
        ("golden light", "golden_hour"),
        ("sunset", "golden_hour"),
        ("sunrise", "golden_hour"),
        ("black and white", "monochrome"),
        ("black & white", "monochrome"),
        ("b&w", "monochrome"),
        ("black-and-white", "monochrome"),
        ("grayscale", "monochrome"),
        ("monochrome", "monochrome"),
        ("desaturated", "desaturated"),
        ("washed out", "desaturated"),
        ("washed-out", "desaturated"),
        ("faded colors", "desaturated"),
        ("muted colors", "muted"),
        ("muted", "muted"),
        ("subdued", "muted"),
        ("vibrant", "vibrant"),
        ("colorful", "vibrant"),
        ("saturated", "vibrant"),
        ("vivid", "vibrant"),
        ("noir", "dark"),
        ("shadowy", "dark"),
        ("dim", "dark"),
        ("dark", "dark"),
        ("bright", "bright"),
        ("well lit", "bright"),
        ("well-lit", "bright"),
        ("sunny", "bright"),
        ("daylight", "bright"),
        ("blue tint", "cold"),
        ("blue cast", "cold"),
        ("cool tones", "cold"),
        ("icy", "cold"),
        ("cold", "cold"),
        ("warm", "warm"),
        ("amber", "warm"),
        ("golden glow", "warm"),
        ("orange glow", "warm"),
        ("neon", "neon"),
        ("cyberpunk", "neon"),
        ("tungsten", "tungsten"),
        ("incandescent", "tungsten"),
        ("practical lights", "tungsten"),
        ("naturalistic", "naturalistic"),
        ("true to life", "naturalistic"),
        ("overexposed", "overexposed"),
        ("over-exposed", "overexposed"),
        ("blown out", "overexposed"),
        ("blown-out", "overexposed"),
        ("underwater", "underwater"),
        ("submerged", "underwater"),
        ("fluorescent", "fluorescent"),
        ("office lighting", "fluorescent"),
    ],
    "lighting": [
        ("low key", "low_key"),
        ("low-key", "low_key"),
        ("chiaroscuro", "low_key"),
        ("noir", "low_key"),
        ("noir lighting", "low_key"),
        ("high key", "high_key"),
        ("high-key", "high_key"),
        ("natural light", "natural"),
        ("natural lighting", "natural"),
        ("sunlight", "natural"),
        ("sun light", "natural"),
        ("moonlight", "moonlight"),
        ("moon light", "moonlight"),
        ("moonlit", "moonlight"),
        ("night light", "moonlight"),
        ("neon lighting", "neon"),
        ("neon lights", "neon"),
        ("artificial", "artificial"),
        ("man made light", "artificial"),
        ("man-made light", "artificial"),
        ("spotlight", "spotlight"),
        ("spot light", "spotlight"),
        ("beam of light", "spotlight"),
        ("stage light", "spotlight"),
        ("backlit", "backlit"),
        ("back lit", "backlit"),
        ("back-lit", "backlit"),
        ("silhouette", "backlit"),
        ("rim light", "backlit"),
        ("candlelight", "candlelight"),
        ("candle light", "candlelight"),
        ("candles", "candlelight"),
        ("diffused", "diffused"),
        ("soft light", "diffused"),
        ("soft lighting", "diffused"),
        ("overcast", "diffused"),
        ("cloudy day", "diffused"),
    ],
}

_compile_cache = {}


def _compile_phrases(category):
    if category not in _compile_cache:
        phrases = sorted(FILTER_SYNONYMS.get(category, []), key=lambda p: -len(p[0]))
        _compile_cache[category] = [
            (re.compile(r"\b" + re.escape(phrase) + r"\b"), value)
            for phrase, value in phrases
        ]
    return _compile_cache[category]


def parse_filters_from_text(text):
    """Extract filter selections mentioned in free text.

    Returns a dict of {category: [value, ...]} in the same shape the API expects.
    """
    if not text:
        return {}
    lowered = text.lower()
    detected = {}
    for category in CATEGORIES:
        found = []
        for pattern, value in _compile_phrases(category):
            if pattern.search(lowered) and value not in found:
                found.append(value)
        if not found:
            continue
        # Drop generic options subsumed by a more specific match.
        subsumed = SUBSUMES.get(category, {})
        pruned = [v for v in found if not any(
            v in subsumed.get(spec, set()) for spec in found
        )]
        if pruned:
            detected[category] = pruned
    return detected
